# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/

name: 'A-S Update Helper'

on:
  pull_request:
    paths: 'Dependencies.kt'
    branches: [ main ]

jobs:
  asVersionChanged:
    name: 'A-S Version Changed'
    runs-on: ubuntu-20.04
    outputs:
      versionChanged: ${{ steps.changeCheck.outputs.didChange }}
    steps:
      - id: changeCheck
        name: 'Check if A-S version changed'
        run: echo "::set-output name=versionChanged::true"
  changeHelper:
    name: 'Post A-S update checklist'
    needs: asVersionChanged
    runs-on: ubuntu-20.04
    #if: ${{ needs.asVersionChanged.outputs.versionChanged }}
    steps:
      - id: postComment
        name: 'Post A-S update checklist'
        uses: JungWinter/comment@v1.1.0
        with:
          type: create
          body: "A-S version changed"
          issue_number: ${{ github.event.issue.number }}"
          token: ${{ secrets.GITHUB_TOKEN }}
